<#
.SYNOPSIS
    Creates a Microsoft Purview DLP policy and rule that block (or audit) sensitive
    information in prompts and responses to custom AI applications and agents.

.DESCRIPTION
    This sample is a starting point for customers who need to set up a Microsoft
    Purview Data Loss Prevention (DLP) policy to test DLP integration with their
    custom AI app, as described in the official guidance:

    https://learn.microsoft.com/en-us/purview/developer/configurepurview
        ("To set up a new DLP policy in Microsoft Purview to test DLP integration,
         run the New-DlpComplianceRule cmdlet.")

    The policy is scoped to one or more Microsoft Entra application registrations
    via the "Application" enforcement plane. The rule blocks UploadText and
    DownloadText activities when content matches the listed sensitive information
    types, and notifies the configured recipients.

    Update every value in the Configuration section below before running.

.NOTES
    Prerequisites:
      - PowerShell 7+
      - ExchangeOnlineManagement module
      - A Microsoft Purview compliance administrator role
      - Each custom AI app registered in Microsoft Entra ID, with its Application
        (client) ID known.

    References:
      - New-DlpCompliancePolicy: https://learn.microsoft.com/powershell/module/exchange/new-dlpcompliancepolicy
      - New-DlpComplianceRule:   https://learn.microsoft.com/powershell/module/exchange/new-dlpcompliancerule
      - Connect-IPPSSession:     https://learn.microsoft.com/powershell/exchange/connect-to-scc-powershell
#>

$ErrorActionPreference = "Stop"

# -----------------------------------------------------------------------------
# Configuration - replace every placeholder with values for your tenant.
# -----------------------------------------------------------------------------

# Friendly names for the policy and rule shown in the Microsoft Purview portal.
$DlpPolicyName = "Contoso Custom AI Apps - Block Sensitive Data"
$DlpRuleName   = "Block sensitive info in custom AI apps"

# Enforcement mode for the policy:
#   Enable     - policy is active and actions are enforced
#   TestWithNotifications - test mode that surfaces matches and sends notifications
#   TestWithoutNotifications - test mode without notifications
#   Disable    - policy exists but does not run
$PolicyMode = "Enable"

# Action the rule applies on a match. Set to "Block" to deny the request, or
# "Audit" to log only.
$RestrictAction = "Block"

# Each custom AI app to scope the policy to. AppId is the Microsoft Entra
# application (client) ID; AppName is a display name shown in the Purview portal.
$Applications = @(
    @{
        AppId   = "11111111-1111-1111-1111-111111111111"
        AppName = "Contoso Custom AI App 1"
    },
    @{
        AppId   = "22222222-2222-2222-2222-222222222222"
        AppName = "Contoso Custom AI App 2"
    }
)

# Recipients for alerts, incident reports, and end-user notifications. Use the
# string "SiteAdmin" to send to the tenant's compliance admins, or replace with
# specific UPNs.
$AlertRecipients     = @("SiteAdmin")
$IncidentRecipients  = @("SiteAdmin")
$NotifyRecipients    = @("SiteAdmin")

# Severity of incidents generated by this rule (Low | Medium | High).
$ReportSeverityLevel = "High"

# Sensitive information types to detect. Add, remove, or change names and
# thresholds to fit your tenant. Names must match Microsoft Purview SIT names.
$SensitiveTypes = @(
    @{ Name = "Credit Card Number";                                  minCount = "1" },
    @{ Name = "U.S. Social Security Number (SSN)";                   minCount = "1" },
    @{ Name = "U.S. Bank Account Number";                            minCount = "1" },
    @{ Name = "U.S. Individual Taxpayer Identification Number (ITIN)"; minCount = "1" },
    @{ Name = "Passport Number";                                     minCount = "1" },
    @{ Name = "IBAN"                                               ; minCount = "1" }
)

# -----------------------------------------------------------------------------
# Connect to Security & Compliance PowerShell
# -----------------------------------------------------------------------------

Write-Host "Connecting to Security & Compliance PowerShell..." -ForegroundColor Cyan
if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) {
    throw "ExchangeOnlineManagement module is not installed. Run: Install-Module ExchangeOnlineManagement -Scope CurrentUser"
}
Import-Module ExchangeOnlineManagement -ErrorAction Stop
Connect-IPPSSession

# -----------------------------------------------------------------------------
# Build the Locations JSON that scopes the policy to the listed Entra apps.
# -----------------------------------------------------------------------------

$LocationsObject = foreach ($app in $Applications) {
    @{
        Workload            = "Applications"
        Location            = $app.AppId
        LocationDisplayName = $app.AppName
        LocationSource      = "Entra"
        LocationType        = "Individual"
        Inclusions          = @(@{ Type = "Tenant"; Identity = "All" })
    }
}
$LocationsJson = $LocationsObject | ConvertTo-Json -Depth 6 -Compress

# -----------------------------------------------------------------------------
# Create or update the DLP policy
# -----------------------------------------------------------------------------

Write-Host "Ensuring DLP policy '$DlpPolicyName' exists..." -ForegroundColor Yellow
$existingPolicy = Get-DlpCompliancePolicy -Identity $DlpPolicyName -ErrorAction SilentlyContinue
if (-not $existingPolicy) {
    New-DlpCompliancePolicy `
        -Name              $DlpPolicyName `
        -Comment           "Blocks common sensitive information types in custom AI apps and agents." `
        -Locations         $LocationsJson `
        -EnforcementPlanes @("Application") `
        -Mode              $PolicyMode | Out-Null
    Write-Host "DLP policy created." -ForegroundColor Green
}
else {
    Set-DlpCompliancePolicy `
        -Identity          $DlpPolicyName `
        -Locations         $LocationsJson `
        -EnforcementPlanes @("Application") `
        -Mode              $PolicyMode | Out-Null
    Write-Host "DLP policy updated." -ForegroundColor Green
}

# -----------------------------------------------------------------------------
# Create or update the DLP rule
# -----------------------------------------------------------------------------

Write-Host "Ensuring DLP rule '$DlpRuleName' exists..." -ForegroundColor Yellow
$existingRule = Get-DlpComplianceRule -Identity $DlpRuleName -ErrorAction SilentlyContinue

$ruleParams = @{
    ContentContainsSensitiveInformation = $SensitiveTypes
    GenerateAlert                       = $AlertRecipients
    GenerateIncidentReport              = $IncidentRecipients
    IncidentReportContent               = @("Default","Detections","DetectionDetails","MatchedItem","RulesMatched","Service","Severity","Title")
    NotifyUser                          = $NotifyRecipients
    ReportSeverityLevel                 = $ReportSeverityLevel
    RestrictAccess                      = @(
        @{ Setting = "UploadText";   Value = $RestrictAction },
        @{ Setting = "DownloadText"; Value = $RestrictAction }
    )
    StopPolicyProcessing                = $true
    Comment                             = "Blocks prompts and responses containing the listed sensitive information types."
}

if (-not $existingRule) {
    New-DlpComplianceRule -Name $DlpRuleName -Policy $DlpPolicyName @ruleParams | Out-Null
    Write-Host "DLP rule created." -ForegroundColor Green
}
else {
    Set-DlpComplianceRule -Identity $DlpRuleName @ruleParams | Out-Null
    Write-Host "DLP rule updated." -ForegroundColor Green
}

# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

Write-Host "`nVerification:" -ForegroundColor Cyan
Get-DlpCompliancePolicy -Identity $DlpPolicyName | Format-List Name, Mode, EnforcementPlanes, Locations
Get-DlpComplianceRule   -Identity $DlpRuleName   | Format-List Name, Policy, RestrictAccess, ReportSeverityLevel
